tasks:
  - before: >
      ssh-keyscan github.com >> ~/.ssh/known_hosts
  - init: git remote set-url origin git@github.com:pavithra-nagarajan/pavithra-nagarajan-sample-foundations-baseline.git
  - name: husky dependency
  - init: npm install husky --save-dev && npx husky install && npm pkg set scripts.prepare="husky install" && npx husky add .husky/post-commit "git log -1 --shortstat > history_log.txt" && npx husky add .husky/pre-commit "chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub"
  - init: git remote set-url origin git@github.com:keynecleetus/sample-foundations-baseline.git
  - name: husky dependency
  - init: npm install husky --save-dev && npx husky install && npm pkg set scripts.prepare="husky install" && npx husky add .husky/post-commit "git log -1 --shortstat > history_log.txt" && npx husky add .husky/pre-commit "chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts"
vscode:
 extensions:
   - kyntrack.gitpod-plugin
vscode:
 extensions:
   - kyntrack.gitpod-plugin